### ISSUE TITLE
Simple Math/Calculus of DevOps

### ISSUE THREAD

**Issue by carmendeardo** [carmendeardo/standing-on-shoulders#1]

**Comment by jackin614** [comment]
I see the math for Tx+...    but there is also a Trust equation with numbers resulting in 32%Trust.  I think there's a graphic that didn't make it.   What is the equation in text so I can drop it in, please?

**Comment by carmendeardo** [comment]
Well here's what Lee writes which I assume you read.  It's basically the percent accurate and complete of the items (or the key items) in the handoff steps associated in the numerator.  

--------------------------------------------------------------------------------------------------
That is, the Tasks we do in a delivery cycle are impacted by the degree of trust we have in the hand-offs from one to another. If we have zero trust then our TDELIVERY will be infinite (divide by zero). 100% trust and our TDELIVERY will be only limited by how fast each task can be performed.
 
Check this scenario that represents what we’re hearing from our clients in the workshops:
 
“On a given project team the plan has about a 50/50 chance of being right, and the design is about 85% right, and the developers will get about 90% of the implementation right, and the testers have about 90% of the test cases right, and the release team has about 95% reliability of having the right stuff together to release, then your trust factor is something like
 
.5 x .85 x .9 x .9 x .95 = 32% Trust”   (and that’s much better than what we usually hear)

**Comment by carmendeardo** [comment]
so each of those handoffs is a multiplying factor like in a electrical series of switches.   If there's 7 steps then there's 6 handoffs and a trust factor in each handoff.  If each one is 90% correct then it's .9 to the sixth power which is only 53%.   Call me if this doesn't compute.  thx

**Comment by jackin614** [comment]
Face palm....   got it... 
Plan 50% x Design 85% x Implementation 90% x Test Cases 90% x Release 95% = Trust
