### ISSUE TITLE
From Dickens to DevOps

### ISSUE THREAD

**Issue by carmendeardo** [carmendeardo/standing-on-shoulders#14]

**Comment by carmendeardo** [comment]
@jackin614 original ready for incorporation into shoulders - I realize the long form might not be relevant so do as you see fit - thx 

I attached the short form from linked-in 
[EDITED From Dickens to DevOps article.pages .docx](https://github.com/carmendeardo/standing-on-shoulders/files/1869468/EDITED.From.Dickens.to.DevOps.article.pages.docx)

**Comment by jackin614** [comment]
I pulled in the short version.  Also want to go back and look at what was left on the cutting room floor...

**Comment by jackin614** [comment]
I liked most (all?) of what was on the floor.  Dropped it into an appendix.
