### ISSUE TITLE
Misc Topics to consider 

### ISSUE THREAD

**Issue by carmendeardo** [carmendeardo/standing-on-shoulders#15]
- From Dorothy to DevOps (took a crisis to address an issue, looked for it externally, solution was actually in her back yard - like the ideas our teams have in the experiments)
- other movie analogies (Mister Mom - 220/221 whatever it takes)
- Slowest common denominator 
- sports (basketball coach can't see the game but has to go by stats to improving shooting percentage)
- autobahn  (article with Jason)

**Comment by jackin614** [comment]
Sounds interesting, we should discuss each and where it should go.

Also:
- review what we have (~25k words now) and what we still need to cover
    - no desire to "pad" for length, cool with up to 200 pages, need to consider impact(s) (if any to too long)
    - definitely want more illustrations, e.g. Integrated Pipeline and tool landscape(s)

- review of issues vs. content (not sure I see all the match-ups)

- Overall review of draft for clarity, structure, completeness / missing components

**Comment by carmendeardo** [comment]
@jackin614 here's the article I wrote with Jason two years ago
https://devops.com/what-auto-industry-can-teach-it-development/

If you think there's anything worth here salvaging
