### ISSUE TITLE
Project and Products

### ISSUE THREAD

**Issue by carmendeardo** [carmendeardo/standing-on-shoulders#5]

**Comment by carmendeardo** [comment]
@jackin614 ready for incorporation into Shoulders - thx

**Comment by jackin614** [comment]
incorporated, will do commits and merges now

**Comment by jackin614** [comment]
still needs a fair amount of discussion to make sure we button up (notes within doc)

**Comment by carmendeardo** [comment]
Ok thanks Jack - will take a look at it.
