### ISSUE TITLE
Applying the Theory of Constraints

### ISSUE THREAD

**Issue by carmendeardo** [carmendeardo/standing-on-shoulders#6]

**Comment by carmendeardo** [comment]
Gene's diagram about deployments per dev per day
- continue telling GOAL story about the robots
- include food bank example (it's the apple sauce stupid!)
- talk about Dominica concepts - too much WIP
- Kingman diagram
- Human resource consumption

**Comment by carmendeardo** [comment]
@jackin614 this still might be relevant to fit in somewhere?  If not, feel free to close this 

Goal story - KPI about robot utilization and keeping  robots 100% busy.  Turns out if robot utilization was over 35%, the downstream stream couldn't keep up.  So the company was wasting money buying raw materials to keep robots busy to produce downstream inventory that couldn't be consumed.  KPI was not aligned to "the goal" of making the company more profitable.

Kingman diagram is basically the hockey stick that shows delay of getting something done goes up dramatically when the resource (including humans) utilization increases due to too much WIP.  The equation is basically , response time = service time / (1 - utilization).   So something with a service time of 5 units (e.g. seconds), has a response time of 5 when the resource is idle.  It goes up to 10 when the resource is 50% utilized, 50 when the resource utilization reaches 90% and 500 at 99% utilization.   While we apply these concepts to machine resources (e.g CPU and Disk) we don't apply them to Human Resources.  Consider the Clarity booking allocations of keeping resources or teams booked at 100% or even 80%.

Food Bank goes along with Robot example in that we don't need more boxes made (or more pallets to load completed packages onto the truck) when it's really the loading of canned/jar/heavy goods like apple sauce that is the constraint on the line.  When you improve something to the left of a bottleneck, you create more inventory buildup before the bottleneck (boxes).  When you improve something to the right/downstream of the bottleneck, you increase the idleness of downstream resources (pallets).  These are local optimizations that are a form of waste.  They waste money on materials and they create more idle/waste of Human Resources.

**Comment by jackin614** [comment]
I have inserted above, but def needs additional cleanup editing

thinking 4 diagrams actually - (1) highway with exits and complications + (2) autobahn, (3) bridge showing supports vs. suspensions + (4) double decker bridge (train deck = streamlined technology & upper deck for 'all other'

**Comment by jackin614** [comment]
![bridge4](https://user-images.githubusercontent.com/37700123/38471325-8061c938-3b3d-11e8-9162-52b3c8fbd413.png)
![supporting the value stream](https://user-images.githubusercontent.com/37700123/38471326-80726ae0-3b3d-11e8-8456-a89b92259450.jpg)

I think one is good, but not sure about the other, would like your thoughts

**Comment by jackin614** [comment]
Gotcha, yep it needs work!   I forgot to show the value flow (horizontal) and didn't even think about Plan - Build - Run.   I will put some words around it too (not literally) to talk about how the support of Funding, Architecture and Prioritization, reinforced with our Culture hold up the value stream while the foundational / functional supports hold up the whole thing.

Struggling with the highway diagrams, but will keep after it.
