### ISSUE TITLE
Value Stream Architecture

### ISSUE THREAD

**Issue by carmendeardo** [carmendeardo/standing-on-shoulders#8]

**Comment by carmendeardo** [comment]
Include some basic concepts - reference Mik's book - also include the organization model implications

**Comment by jackin614** [comment]
added after S-M-L discussion in How:

Architecting our Future State
As we get down to the nuts and bolts of planning our future state, there are a couple of things that we need to add, that were probably not on our landscape before.   Future you will want to kick current you if you don’t layer them in now, for sure.
Architecture is our first actual step on this journey, up until now it’s been preparation and consideration.  Our architecture needs to address several core needs:
•	Speed
•	Resilience
•	Future Proofing
Architecting for Speed
As we lay out our Value Stream Maps, we…
